wip - update code to comply new shepherd action's api

diff --git a/.github/workflows/create-bosh-release.yml b/.github/workflows/create-bosh-release.yml
--- a/.github/workflows/create-bosh-release.yml
+++ b/.github/workflows/create-bosh-release.yml
@@ -45,29 +45,43 @@ jobs:
     #     github_token: ${{ secrets.GITHUB_TOKEN }}
     #     branch: ${{ github.ref }}
 
-    - name: Claim test environment
-      id:   claim-env
+    - name: Create test environment
+      id:   create-env
+      if:   ${{ !vars.ENV_ID }}
       uses: a-b/gha-shepherd@main
       with:
-        debug:        ${{ runner.debug }}
-        api_token:    ${{ secrets.SHEPHERD_API_TOKEN }}
-        api_endpoint: ${{ vars.SHEPHERD_API_ENDPOINT }}
-        pool_name:      cfd
+        api_endpoint  : ${{ vars.SHEPHERD_API_ENDPOINT }}
+        api_token     : ${{ secrets.SHEPHERD_API_TOKEN }}
+        command       : create
+        debug         : ${{ runner.debug }}
+        duration      : 1h
+        namespace     : tas-devex
+        pool_name     : cfd
         pool_namespace: official
-        namespace:      tas-devex
-        duration:       4h
 
-    - name: Store lease data
-      uses: actions/upload-artifact@v4
+    - name: Get running env metadata
+      uses: a-b/gha-shepherd@main
       with:
-        name: lease-json
-        path: lease.json
+        api_endpoint : ${{ vars.SHEPHERD_API_ENDPOINT }}
+        api_token    : ${{ secrets.SHEPHERD_API_TOKEN }}
+        command      : get
+        debug        : ${{ runner.debug }}
+        env_file_path: ./lease.json
+        env_id       : ${{ vars.ENV_ID || steps.create-env.outputs.env-id }}
+        namespace    : tas-devex
 
-    # use previous lease data to reuse leased environment
-    - name: Retrieve lease data
-      uses: actions/download-artifact@v4
-      with:
-        name: lease-json
+
+    # - name: Store lease data
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: lease-json
+    #     path: lease.json
+
+    # # use previous lease data to reuse leased environment
+    # - name: Retrieve lease data
+    #   uses: actions/download-artifact@v4
+    #   with:
+    #     name: foobar
 
     - name: Deploy and run tests
       run: |
@@ -118,68 +132,97 @@ jobs:
         bosh clean-up --all
 
     - name: Upload test results
-      uses: actions/upload-artifact@v4
+      uses: actions/upload-artifact@v3
       with:
         name: test-results
         path: /tmp/cf-cli-*-test.out
     
-    - name: Verify test results
-      run: |
-        set -x -o errexit -o nounset -o pipefail
+  # verify_test_results:
+  #   runs-on: ubuntu-latest
+  #   # container:
+  #   #   image: "ghcr.io/chinigorg/bosh-package-cf-cli-release-ci:187042013-release-workflow-latest"
 
-        for test_result in /tmp/cf-cli-*-test.out; do
-          echo "Test result: $test_result"
+  #   steps:
 
-          grep -e Stdout -e Stderr -e "Exit Code" $test_result
+  #   - name: Checkout cli bosh release repo
+  #     uses: actions/checkout@v3
 
-          # if grep -q "failed" $test_result; then
-          #   echo "Test failed: $test_result"
-          #   exit 1
-          # fi
-        done
+  #   - name: Download test results
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: test-results
+  #       path: /tmp #${{ runner.tmp }}
 
-    # # # ## Finalize bosh release
-    # # # ## Get final release from assets
-    # # # ## Push commit with final release
-    # # # - name: Finalize bosh release
-    # # #   if: steps.create-bosh-release-candidate-step.outputs.blobs_updated == 'yes'
-    # # #   env:
-    # # #     TRACE: ${{ runner.debug }}
-    # # #   run: |
-    # # #     set -o errexit -o nounset -o pipefail
-    # # #     [[ "${TRACE:-0}" == "1" ]] && set -o xtrace
+  #   # - run: |
+  #   #     echo "foobar7" > /tmp/cf-cli-7-test.out
+  #   #     echo "foobar8" > /tmp/cf-cli-7-test.out
 
-    # # #     if [[ "${{ steps.create-bosh-release-candidate-step.outputs.blobs_updated }}" == "yes" ]]; then
 
-    # # #     echo "Bosh Blobs: initial state"
-    # # #     bosh blobs
+  #   - name: Display structure of downloaded files
+  #     run: |
+  #       pwd
+  #       unzip test-results.zip
+  #       ls -R
+  #     working-directory: /tmp # ${{ runner.tmp }}
 
-    # # #     ## Determine next release version number
+  #   # - name: Verify test results
+  #   #   run: |
+  #   #     echo =====
+  #   #     ls 
+  #   # #     set -x -o errexit -o nounset -o pipefail
+  #   # #     for test_result in /tmp/cf-cli-*-test.out; do
+  #   # #       echo "Test result: $test_result"
+  #   # #       # grep -e Stdout -e Stderr -e "Exit Code" $test_result
+  #   # #       grep -e foo $test_result
+  #   # #       # if grep -q "failed" $test_result; then
+  #   # #       #   echo "Test failed: $test_result"
+  #   # #       #   exit 1
+  #   # #       # fi
+  #   # #     done
 
-    # # #     RELEASE_VERSION=$(cat release-version/version)
-    # # #     git config --global --add safe.directory "$(pwd)"
-    # # #     git config user.name  "github-actions[bot]"
-    # # #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com "
+  #   # # # # # ## Finalize bosh release
+  #   # # # # # ## Get final release from assets
+  #   # # # # # ## Push commit with final release
+  #   # # # # # - name: Finalize bosh release
+  #   # # # # #   if: steps.create-bosh-release-candidate-step.outputs.blobs_updated == 'yes'
+  #   # # # # #   env:
+  #   # # # # #     TRACE: ${{ runner.debug }}
+  #   # # # # #   run: |
+  #   # # # # #     set -o errexit -o nounset -o pipefail
+  #   # # # # #     [[ "${TRACE:-0}" == "1" ]] && set -o xtrace
 
-    # # #     bosh create-release --final --version="${RELEASE_VERSION}" --tarball="./cf-cli-v${RELEASE_VERSION}.tgz"
+  #   # # # # #     if [[ "${{ steps.create-bosh-release-candidate-step.outputs.blobs_updated }}" == "yes" ]]; then
 
-    # # #     git add --all
-    # # #     git status
-    # # #     git commit -m "create final release ${RELEASE_VERSION}"
+  #   # # # # #     echo "Bosh Blobs: initial state"
+  #   # # # # #     bosh blobs
 
-    # # #     ls -lah ./candidate-release-output/cf-cli-dev-release.tgz
+  #   # # # # #     ## Determine next release version number
 
-    # - name: Unclaim environment with provided env_id and namespace
-    #   if:   always() && !runner.debug
-    #   uses: a-b/gha-shepherd@main
-    #   with:
-    #     debug:        ${{ runner.debug }}
-    #     api_token:    ${{ secrets.SHEPHERD_API_TOKEN }}
-    #     api_endpoint: ${{ vars.SHEPHERD_API_ENDPOINT }}
-    #     env_id:       ${{ steps.claim-env.outputs.env-id }}
-    #     namespace:    tas-devex
+  #   # # # # #     RELEASE_VERSION=$(cat release-version/version)
+  #   # # # # #     git config --global --add safe.directory "$(pwd)"
+  #   # # # # #     git config user.name  "github-actions[bot]"
+  #   # # # # #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com "
 
-    # - name: Setup tmate session
-    #   if: ${{ always() && runner.debug }}
-    #   uses: mxschmitt/action-tmate@v3
-    #   timeout-minutes: 20
+  #   # # # # #     bosh create-release --final --version="${RELEASE_VERSION}" --tarball="./cf-cli-v${RELEASE_VERSION}.tgz"
+
+  #   # # # # #     git add --all
+  #   # # # # #     git status
+  #   # # # # #     git commit -m "create final release ${RELEASE_VERSION}"
+
+  #   # # # # #     ls -lah ./candidate-release-output/cf-cli-dev-release.tgz
+
+  #   # # # - name: Delete lease with provided env_id and namespace
+  #   # # #   if:   ${{ always() && !vars.ENV_ID }}
+  #   # # #   uses: a-b/gha-shepherd@main
+  #   # # #   with:
+  #   # # #     api_endpoint: ${{ vars.SHEPHERD_API_ENDPOINT }}
+  #   # # #     api_token:    ${{ secrets.SHEPHERD_API_TOKEN }}
+  #   # # #     command:      delete
+  #   # # #     debug:        ${{ runner.debug }}
+  #   # # #     env_id:       ${{ steps.claim-env.outputs.env-id }}
+  #   # # #     namespace:    tas-devex
+
+  #   # # # - name: Setup tmate session
+  #   # # #   if: ${{ always() && runner.debug }}
+  #   # # #   uses: mxschmitt/action-tmate@v3
+  #   # # #   timeout-minutes: 20
