WIP - Use GHA job output

diff --git a/.github/workflows/ensure-ci-image.yml b/.github/workflows/ensure-ci-image.yml
--- a/.github/workflows/ensure-ci-image.yml
+++ b/.github/workflows/ensure-ci-image.yml
@@ -10,26 +10,43 @@ env:
   CI_DOCKERFILE_MOST_RECENT_SHA: # Determined dynamically later on
 
 jobs:
-  build-and-push-ci-image:
+  calculate-latest-label:
     runs-on: ubuntu-latest
+
     permissions:
       contents: read
-      packages: write
+
+    outputs:
+      ci_dockerfile_latest_sha: ${{ steps.calculate_latest_sha.outputs.ci_dockerfile_latest_sha }}
 
     steps:
     - name: Checkout repo
       uses: actions/checkout@v4
 
     - name: Calculate label for CI image
+      id: calculate_latest_sha
       env:
         IMAGE_NAME: ${{ github.repository }}
       run: |
         dockerfile_path=${CI_DOCKERFILE_DIR}/${CI_DOCKERFILE_PATH}
 
-        [[ ! -f ${dockerfile_path} ]] && echo "Could not find Dockerfile at ${dockerfile_path}" && exit 1
+        [[ ! -f ${dockerfile_path} ]] && echo "Could not find Dockerfile at ${dockerfile_path}" 1>&2 && exit 1
 
-        echo "CI_DOCKERFILE_MOST_RECENT_SHA=$(git log --pretty=format:%H "${dockerfile_path}")" >> $GITHUB_ENV
-        cat "${GITHUB_ENV}"
+        echo "ci_dockerfile_latest_sha=$(git log --pretty=format:%H "${dockerfile_path}")" >> $GITHUB_OUTPUT
+
+  build-and-push-ci-image:
+    runs-on: ubuntu-latest
+
+    permissions:
+      contents: read
+      packages: write
+
+    needs:
+    - calculate-latest-label
+
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@v4
 
     - name: Login to GitHub container registry
       uses: docker/login-action@v3
@@ -47,7 +64,7 @@ jobs:
       with:
         images: ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}-ci
         tags: |
-          ${{ env.CI_DOCKERFILE_MOST_RECENT_SHA }}
+          type=raw,value=${{ needs.calculate-latest-label.outputs.ci_dockerfile_latest_sha }}
           ${{ github.ref_name }}-latest
 
     - name: Build and push CI image
